### ISSUE TITLE
hotkey trigger broken - worked lovely till Obsidian 13.10's new editor 

### ISSUE THREAD

**Issue by Sigbert11** [oeN/liquid-template#4]
used to be an excellent buddy for templating till the new Obsidian live preview editor functionality.
When switching back to legacy editor all is fine as before.

Could you re-enable the plugins functionality under the new Obsidian 13.10+ editor

**Comment by oeN** [comment]
Hi, thanks for opening the issue, I'll look into it in the next few days.
sorry for the late response 😅
